import { DataModel, Model, isDataModel } from '@zenstackhq/sdk/ast';
import { mermaidGenerator, policyGenerator } from '.';

export async function generate(model: Model) {
    const dataModels = model.declarations.filter((x) => isDataModel(x) && !x.isAbstract) as DataModel[];

    const headings = dataModels.map((x) => `- [${x.name}](#${x.name})`).join('\n');

    const modelChapter = dataModels
        .map((x) => {
            return [`## ${x.name}`, mermaidGenerator.generate(x), policyGenerator.generate(x)].join('\n');
        })
        .join('\n');

    const content = [
        '# Technical Design Document',
        '> Generated by [`ZenStack-markdown`](https://github.com/jiashengguo/zenstack-markdown)',
        headings,
        modelChapter,
    ].join('\n\n');

    return content;
}
